#include <cxxtest/TestSuite.h>
#include "../src/MacGetVelocity.h"
#include "../src/MacInitializeCell.h"
#include "../src/MacWorld.h"
#include "../src/MacCell.h"
#include "../src/Physvector.h"
#include "../src/PhysvectorKeyOrder.h"
#include "../src/TableContainerList.h"
#include "../src/KeyTableMap.h"
#include "../src/Particle.h"
#include "../src/MacGetStagPos.h"
#include "../src/GetCellType.h"
#include "../src/Mac_1_Order_UpWindConvect.h"
#define eps 1e-10
class Test_Mac_1_OrderUpWindConvect : public CxxTest::TestSuite
{
	public:
	void testconst1d()
	{
		typedef Physvector<1,int> keyvect;
		typedef Physvector<1,double> vect;
		typedef Particle<vect> part;
		typedef MacCell<1,double,int> mac;
		typedef TableContainerList<part> list_part;
		typedef PhysvectorKeyOrder<1,int> order;
		typedef KeyTableMap<keyvect,mac,order> keytable;
		typedef MacWorld<keytable,list_part> world;
		typedef GetCellType<world> type_getcelltype;
		Physvector<1,double> temp;
		temp.Set(1,2.0);
		mac c1(temp,0,1,0);
		mac c2(temp,0,0,1);
		mac c3(temp,0,0,1);
		order o;
		keytable k(o);
		Physvector<1,int> vkey;
		vkey.Set(1,0);
		k[vkey]=c1;
		vkey.Set(1,1);
		k[vkey]=c2;
		vkey.Set(1,-1);
		k[vkey]=c3;
		list_part lp;
		world W(k,lp);
		int m_air=0;
		int m_fluid=1;
		int m_boundary_air=2;
		int m_boundary_fluid=3;
		double m_rho_fluid=1000;
		double m_rho_air=1;
		double m_1_rho_fluid=0.001;
		double m_1_rho_air=1;
		double m_rho_inter=1000;
		double m_rho_inter_bound=1000;
		double m_1_rho_inter=0.001;
		double m_1_rho_inter_bound=0.001;
		type_getcelltype m_GetCellType(W,m_fluid,m_boundary_fluid,m_air,m_boundary_air,m_rho_fluid,m_rho_air,m_1_rho_fluid,m_1_rho_air,m_rho_inter,m_1_rho_inter,m_rho_inter_bound,m_1_rho_inter_bound);
		Physvector<1,double>  vh;
		vh.Set(1,1.0);
		typedef MacGetStagPos<world>  type_stag;
		type_stag stag(vh);
		typedef MacGetVelocity<world,type_stag > type_vel;
		type_vel Nlin(W,stag,vh);
		double dt=0.2;
		Physvector<1,double> h;
		Physvector<1,double> _1_h;
		h.SetAll(1);
		_1_h.SetAll(1);
		Mac_1_Order_UpWindConvect<world,type_vel,type_stag,type_getcelltype > Conv(W,Nlin,stag,dt,m_GetCellType,h,_1_h);
		Conv.Calculate();
		vkey.Set(1,0);
		Physvector<1,double> vtemp;
		W.m_mac_grid[vkey].GetSpeed(vtemp);
		TS_ASSERT_DELTA(vtemp.Get(1),2,eps);
		vkey.Set(1,1);
		W.m_mac_grid[vkey].GetSpeed(vtemp);
		TS_ASSERT_DELTA(vtemp.Get(1),2,eps);
		vkey.Set(1,-1);
		W.m_mac_grid[vkey].GetSpeed(vtemp);
		TS_ASSERT_DELTA(vtemp.Get(1),2,eps);
	}
	
	void testVar1d()
	{
		typedef Physvector<1,int> keyvect;
		typedef Physvector<1,double> vect;
		typedef Particle<vect> part;
		typedef MacCell<1,double,int> mac;
		typedef TableContainerList<part> list_part;
		typedef PhysvectorKeyOrder<1,int> order;
		typedef KeyTableMap<keyvect,mac,order> keytable;
		typedef MacWorld<keytable,list_part> world;
		typedef GetCellType<world> type_getcelltype;
		Physvector<1,double> temp;
		temp.Set(1,2.0);
		mac c1(temp,0,1,0);
		Physvector<1,double> temp2;
		temp2.Set(1,1.0);
		mac c2(temp2,0,0,1);
		Physvector<1,double> temp3;
		temp3.Set(1,0.5);
		mac c3(temp3,0,0,1);
		order o;
		keytable k(o);
		Physvector<1,int> vkey;
		vkey.Set(1,0);
		k[vkey]=c1;
		vkey.Set(1,1);
		k[vkey]=c2;
		vkey.Set(1,-1);
		k[vkey]=c3;
		list_part lp;
		world W(k,lp);
		int m_air=0;
		int m_fluid=1;
		int m_boundary_air=2;
		int m_boundary_fluid=3;
		double m_rho_fluid=1000;
		double m_rho_air=1;
		double m_1_rho_fluid=0.001;
		double m_1_rho_air=1;
		double m_rho_inter=1000;
		double m_rho_inter_bound=1000;
		double m_1_rho_inter=0.001;
		double m_1_rho_inter_bound=0.001;
		type_getcelltype m_GetCellType(W,m_fluid,m_boundary_fluid,m_air,m_boundary_air,m_rho_fluid,m_rho_air,m_1_rho_fluid,m_1_rho_air,m_rho_inter,m_1_rho_inter,m_rho_inter_bound,m_1_rho_inter_bound);
		Physvector<1,double>  vh;
		vh.Set(1,1.0);
		typedef MacGetStagPos<world>  type_stag;
		type_stag stag(vh);
		typedef MacGetVelocity<world,type_stag > type_vel;
		type_vel Nlin(W,stag,vh);
		double dt=0.2;
		Physvector<1,double> h;
		Physvector<1,double> _1_h;
		h.SetAll(1);
		_1_h.SetAll(1);
		Mac_1_Order_UpWindConvect<world,type_vel,type_stag,type_getcelltype > Conv(W,Nlin,stag,dt,m_GetCellType,h,_1_h);
		Conv.Calculate();
		vkey.Set(1,0);
		Physvector<1,double> vtemp;
		W.m_mac_grid[vkey].GetSpeed(vtemp);
		TS_ASSERT_DELTA(vtemp.Get(1),1.4,eps);
	}

	void testVarOp1d()
	{
		typedef Physvector<1,int> keyvect;
		typedef Physvector<1,double> vect;
		typedef Particle<vect> part;
		typedef MacCell<1,double,int> mac;
		typedef TableContainerList<part> list_part;
		typedef PhysvectorKeyOrder<1,int> order;
		typedef KeyTableMap<keyvect,mac,order> keytable;
		typedef MacWorld<keytable,list_part> world;
		typedef GetCellType<world> type_getcelltype;
		Physvector<1,double> temp;
		temp.Set(1,-2.0);
		mac c1(temp,0,1,0);
		Physvector<1,double> temp2;
		temp2.Set(1,1.0);
		mac c2(temp2,0,0,1);
		Physvector<1,double> temp3;
		temp3.Set(1,0.5);
		mac c3(temp3,0,0,1);
		order o;
		keytable k(o);
		Physvector<1,int> vkey;
		vkey.Set(1,0);
		k[vkey]=c1;
		vkey.Set(1,1);
		k[vkey]=c2;
		vkey.Set(1,-1);
		k[vkey]=c3;
		list_part lp;
		world W(k,lp);
		int m_air=0;
		int m_fluid=1;
		int m_boundary_air=2;
		int m_boundary_fluid=3;
		double m_rho_fluid=1000;
		double m_rho_air=1;
		double m_1_rho_fluid=0.001;
		double m_1_rho_air=1;
		double m_rho_inter=1000;
		double m_rho_inter_bound=1000;
		double m_1_rho_inter=0.001;
		double m_1_rho_inter_bound=0.001;
		type_getcelltype m_GetCellType(W,m_fluid,m_boundary_fluid,m_air,m_boundary_air,m_rho_fluid,m_rho_air,m_1_rho_fluid,m_1_rho_air,m_rho_inter,m_1_rho_inter,m_rho_inter_bound,m_1_rho_inter_bound);
		Physvector<1,double>  vh;
		vh.Set(1,1.0);
		typedef MacGetStagPos<world>  type_stag;
		type_stag stag(vh);
		typedef MacGetVelocity<world,type_stag > type_vel;
		type_vel Nlin(W,stag,vh);
		double dt=0.2;
		Physvector<1,double> h;
		Physvector<1,double> _1_h;
		h.SetAll(1);
		_1_h.SetAll(1);
		Mac_1_Order_UpWindConvect<world,type_vel,type_stag,type_getcelltype > Conv(W,Nlin,stag,dt,m_GetCellType,h,_1_h);
		Conv.Calculate();
		vkey.Set(1,0);
		Physvector<1,double> vtemp;
		W.m_mac_grid[vkey].GetSpeed(vtemp);
		TS_ASSERT_DELTA(vtemp.Get(1),-0.8,eps);
	}


	void testconst2d()
	{
		typedef Physvector<2,int> keyvect;
		typedef Physvector<2,double> vect;
		typedef Particle<vect> part;
		typedef MacCell<2,double,int> mac;
		typedef TableContainerList<part> list_part;
		typedef PhysvectorKeyOrder<2,int> order;
		typedef KeyTableMap<keyvect,mac,order> keytable;
		typedef MacWorld<keytable,list_part> world;
		typedef GetCellType<world> type_getcelltype;
		Physvector<2,double> temp;
		temp.Set(1,2.0);
		temp.Set(2,4.0);
		mac c1(temp,0,1,0);
		mac c2(temp,0,0,1);
		mac c3(temp,0,0,1);
		mac c4(temp,0,0,1);
		mac c5(temp,0,0,1);
		mac c6(temp,0,0,1);
		order o;
		keytable k(o);
		Physvector<2,int> vkey;
		vkey.Set(1,0);
		vkey.Set(2,0);
		k[vkey]=c1;
		vkey.Set(2,1);
		k[vkey]=c2;
		vkey.Set(2,-1);
		k[vkey]=c3;
		vkey.Set(1,1);
		vkey.Set(2,0);
		k[vkey]=c4;
		vkey.Set(1,-1);
		k[vkey]=c5;
		vkey.Set(1,-1);
		vkey.Set(2,1);
		k[vkey]=c6;
		vkey.Set(1,-2);
		vkey.Set(2,0);
		k[vkey]=c6;
		vkey.Set(1,-1);
		vkey.Set(2,-1);
		k[vkey]=c6;
		vkey.Set(1,0);
		vkey.Set(2,-2);
		k[vkey]=c6;
		vkey.Set(1,1);
		vkey.Set(2,-1);
		k[vkey]=c6;
		vkey.Set(1,2);
		vkey.Set(2,0);
		k[vkey]=c6;
		vkey.Set(1,1);
		vkey.Set(2,1);
		k[vkey]=c6;
		vkey.Set(1,0);
		vkey.Set(2,2);
		k[vkey]=c6;

		vkey.Set(1,-1);
		vkey.Set(2,2);
		k[vkey]=c6;

		vkey.Set(1,-2);
		vkey.Set(2,1);
		k[vkey]=c6;

		vkey.Set(1,-2);
		vkey.Set(2,-1);
		k[vkey]=c6;

		vkey.Set(1,-1);
		vkey.Set(2,-2);
		k[vkey]=c6;

		vkey.Set(1,1);
		vkey.Set(2,-2);
		k[vkey]=c6;

		vkey.Set(1,2);
		vkey.Set(2,-1);
		k[vkey]=c6;

		vkey.Set(1,2);
		vkey.Set(2,1);
		k[vkey]=c6;

		vkey.Set(1,1);
		vkey.Set(2,2);
		k[vkey]=c6;

		list_part lp;
		world W(k,lp);
		int m_air=0;
		int m_fluid=1;
		int m_boundary_air=2;
		int m_boundary_fluid=3;
		double m_rho_fluid=1000;
		double m_rho_air=1;
		double m_1_rho_fluid=0.001;
		double m_1_rho_air=1;
		double m_rho_inter=1000;
		double m_rho_inter_bound=1000;
		double m_1_rho_inter=0.001;
		double m_1_rho_inter_bound=0.001;
		type_getcelltype m_GetCellType(W,m_fluid,m_boundary_fluid,m_air,m_boundary_air,m_rho_fluid,m_rho_air,m_1_rho_fluid,m_1_rho_air,m_rho_inter,m_1_rho_inter,m_rho_inter_bound,m_1_rho_inter_bound);
		Physvector<2,double>  vh;
		vh.SetAll(1.0);
		typedef MacGetStagPos<world>  type_stag;
		type_stag stag(vh);
		typedef MacGetVelocity<world,type_stag > type_vel;
		type_vel Nlin(W,stag,vh);
		double dt=0.2;
		Physvector<2,double> h;
		Physvector<2,double> _1_h;
		h.SetAll(1);
		_1_h.SetAll(1);
		Mac_1_Order_UpWindConvect<world,type_vel,type_stag,type_getcelltype > Conv(W,Nlin,stag,dt,m_GetCellType,h,_1_h);
		Conv.Calculate();
		vkey.Set(1,0);
		vkey.Set(2,0);
		Physvector<2,double> vtemp;
		W.m_mac_grid[vkey].GetSpeed(vtemp);
		TS_ASSERT_DELTA(vtemp.Get(1),2.0,eps);
		TS_ASSERT_DELTA(vtemp.Get(2),4.0,eps);
	}

	void testvar2d()
	{
		typedef Physvector<2,int> keyvect;
		typedef Physvector<2,double> vect;
		typedef Particle<vect> part;
		typedef MacCell<2,double,int> mac;
		typedef TableContainerList<part> list_part;
		typedef PhysvectorKeyOrder<2,int> order;
		typedef KeyTableMap<keyvect,mac,order> keytable;
		typedef MacWorld<keytable,list_part> world;
		typedef GetCellType<world> type_getcelltype;
		Physvector<2,double> temp;
		temp.Set(1,2.0);
		temp.Set(2,4.0);
		mac c1(temp,0,1,0);
		Physvector<2,double> temp2;
		temp2.Set(1,1.0);
		temp2.Set(2,3.0);
		mac c2(temp2,0,0,1);
		Physvector<2,double> temp3;
		temp3.Set(1,4.0);
		temp3.Set(2,8.0);
		mac c3(temp3,0,0,1);
		Physvector<2,double> temp4;
		temp4.Set(1,3.0);
		temp4.Set(2,2.0);
		mac c4(temp4,0,0,1);
		Physvector<2,double> temp5;
		temp5.Set(1,1.0);
		temp5.Set(2,7.0);
		mac c5(temp5,0,0,1);
		Physvector<2,double> temp6;
		temp6.Set(1,0.0);
		temp6.Set(2,0.0);
		mac c6(temp6,0,0,1);
		order o;
		keytable k(o);
		Physvector<2,int> vkey;
		vkey.Set(1,0);
		vkey.Set(2,0);
		k[vkey]=c1;
		vkey.Set(2,1);
		k[vkey]=c2;
		vkey.Set(2,-1);
		k[vkey]=c3;
		vkey.Set(1,1);
		vkey.Set(2,0);
		k[vkey]=c4;
		vkey.Set(1,-1);
		k[vkey]=c5;
		vkey.Set(1,-1);
		vkey.Set(2,1);
		k[vkey]=c6;
		vkey.Set(1,-2);
		vkey.Set(2,0);
		k[vkey]=c6;
		vkey.Set(1,1);
		vkey.Set(2,-1);
		k[vkey]=c6;
		vkey.Set(1,0);
		vkey.Set(2,-2);
		k[vkey]=c6;
		vkey.Set(1,-1);
		vkey.Set(2,-1);
		k[vkey]=c6;
		list_part lp;
		world W(k,lp);
		int m_air=0;
		int m_fluid=1;
		int m_boundary_air=2;
		int m_boundary_fluid=3;
		double m_rho_fluid=1000;
		double m_rho_air=1;
		double m_1_rho_fluid=0.001;
		double m_1_rho_air=1;
		double m_rho_inter=1000;
		double m_rho_inter_bound=1000;
		double m_1_rho_inter=0.001;
		double m_1_rho_inter_bound=0.001;
		type_getcelltype m_GetCellType(W,m_fluid,m_boundary_fluid,m_air,m_boundary_air,m_rho_fluid,m_rho_air,m_1_rho_fluid,m_1_rho_air,m_rho_inter,m_1_rho_inter,m_rho_inter_bound,m_1_rho_inter_bound);
		Physvector<2,double>  vh;
		vh.SetAll(1.0);
		typedef MacGetStagPos<world>  type_stag;
		type_stag stag(vh);
		typedef MacGetVelocity<world,type_stag > type_vel;
		type_vel Nlin(W,stag,vh);
		double dt=0.2;
		Physvector<2,double> h;
		Physvector<2,double> _1_h;
		h.SetAll(1);
		_1_h.SetAll(1);
		Mac_1_Order_UpWindConvect<world,type_vel,type_stag,type_getcelltype > Conv(W,Nlin,stag,dt,m_GetCellType,h,_1_h);
		Conv.Calculate();
		vkey.Set(1,0);
		vkey.Set(2,0);
		Physvector<2,double> vtemp;
		W.m_mac_grid[vkey].GetSpeed(vtemp);
		TS_ASSERT_DELTA(vtemp.Get(1),3.0,eps);
		TS_ASSERT_DELTA(vtemp.Get(2),8.55,eps);
	}
	
	void testvarop2d()
	{
		typedef Physvector<2,int> keyvect;
		typedef Physvector<2,double> vect;
		typedef Particle<vect> part;
		typedef MacCell<2,double,int> mac;
		typedef TableContainerList<part> list_part;
		typedef PhysvectorKeyOrder<2,int> order;
		typedef KeyTableMap<keyvect,mac,order> keytable;
		typedef MacWorld<keytable,list_part> world;
		typedef GetCellType<world> type_getcelltype;
		Physvector<2,double> temp;
		temp.Set(1,-2.0);
		temp.Set(2,-4.0);
		mac c1(temp,0,1,0);
		Physvector<2,double> temp2;
		temp2.Set(1,1.0);
		temp2.Set(2,3.0);
		mac c2(temp2,0,0,1);
		Physvector<2,double> temp3;
		temp3.Set(1,4.0);
		temp3.Set(2,8.0);
		mac c3(temp3,0,0,1);
		Physvector<2,double> temp4;
		temp4.Set(1,3.0);
		temp4.Set(2,2.0);
		mac c4(temp4,0,0,1);
		Physvector<2,double> temp5;
		temp5.Set(1,1.0);
		temp5.Set(2,7.0);
		mac c5(temp5,0,0,1);
		Physvector<2,double> temp6;
		temp6.Set(1,0.0);
		temp6.Set(2,0.0);
		mac c6(temp6,0,0,1);
		order o;
		keytable k(o);
		Physvector<2,int> vkey;
		vkey.Set(1,0);
		vkey.Set(2,0);
		k[vkey]=c1;
		vkey.Set(2,1);
		k[vkey]=c2;
		vkey.Set(2,-1);
		k[vkey]=c3;
		vkey.Set(1,1);
		vkey.Set(2,0);
		k[vkey]=c4;
		vkey.Set(1,-1);
		k[vkey]=c5;
		vkey.Set(1,-1);
		vkey.Set(2,1);
		k[vkey]=c6;
		vkey.Set(1,-2);
		vkey.Set(2,0);
		k[vkey]=c6;
		vkey.Set(1,1);
		vkey.Set(2,-1);
		k[vkey]=c6;
		vkey.Set(1,0);
		vkey.Set(2,-2);
		k[vkey]=c6;
		vkey.Set(1,-1);
		vkey.Set(2,-1);
		k[vkey]=c6;
		list_part lp;
		world W(k,lp);
		int m_air=0;
		int m_fluid=1;
		int m_boundary_air=2;
		int m_boundary_fluid=3;
		double m_rho_fluid=1000;
		double m_rho_air=1;
		double m_1_rho_fluid=0.001;
		double m_1_rho_air=1;
		double m_rho_inter=1000;
		double m_rho_inter_bound=1000;
		double m_1_rho_inter=0.001;
		double m_1_rho_inter_bound=0.001;
		type_getcelltype m_GetCellType(W,m_fluid,m_boundary_fluid,m_air,m_boundary_air,m_rho_fluid,m_rho_air,m_1_rho_fluid,m_1_rho_air,m_rho_inter,m_1_rho_inter,m_rho_inter_bound,m_1_rho_inter_bound);
		Physvector<2,double>  vh;
		vh.SetAll(1.0);
		typedef MacGetStagPos<world>  type_stag;
		type_stag stag(vh);
		typedef MacGetVelocity<world,type_stag > type_vel;
		type_vel Nlin(W,stag,vh);
		double dt=0.2;
		Physvector<2,double> h;
		Physvector<2,double> _1_h;
		h.SetAll(1);
		_1_h.SetAll(1);
		Mac_1_Order_UpWindConvect<world,type_vel,type_stag,type_getcelltype > Conv(W,Nlin,stag,dt,m_GetCellType,h,_1_h);
		Conv.Calculate();
		vkey.Set(1,0);
		vkey.Set(2,0);
		Physvector<2,double> vtemp;
		W.m_mac_grid[vkey].GetSpeed(vtemp);
		TS_ASSERT_DELTA(vtemp.Get(1),1.8,eps);
		TS_ASSERT_DELTA(vtemp.Get(2),4.35,eps);
	}

};
